import [
    Compiler/Token,
    Tool/Peg/ParseTree,
    Tool/Peg/TestPreds,
]

type Terminal = Token
type NonTerminal = NonTerminal

Terminals:
    "a" = Token(kind = TokenKind.LowerId, text = "a", ..)
    "b" = Token(kind = TokenKind.LowerId, text = "b", ..)

items[ItemExts[t]] Vec[Item[t]]:
    items=item+:
        items

item[ItemExts[t]] Item[t]:
    "a": Item.A(x = 0, ..ItemExts[t].defaultA())
    "b": Item.B(msg = "hi", ..ItemExts[t].defaultB())
